/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Company {
  'id' : string,
  'contactName' : string,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'phone' : string,
}
export interface Lead {
  'id' : string,
  'customerName' : string,
  'status' : Status,
  'originAddress' : string,
  'destinationAddress' : string,
  'createdAt' : Time,
  'email' : string,
  'notes' : string,
  'phone' : string,
  'moveDate' : string,
  'moveSize' : MoveSize,
}
export interface LogEntry { 'message' : string, 'timestamp' : Time }
export type MoveSize = { 'studio' : null } |
  { 'twoBR' : null } |
  { 'oneBR' : null } |
  { 'threeBRPlus' : null };
export type Status = { 'new' : null } |
  { 'closed' : null } |
  { 'distributed' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addActivityLog' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignLeadToCompany' : ActorMethod<[string, string], undefined>,
  'createCompany' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'createLead' : ActorMethod<
    [string, string, string, string, string, string, string, MoveSize, string],
    undefined
  >,
  'deleteCompany' : ActorMethod<[string], undefined>,
  'deleteLead' : ActorMethod<[string], undefined>,
  'getActivityLog' : ActorMethod<[string], Array<LogEntry>>,
  'getAllCompanies' : ActorMethod<[], Array<Company>>,
  'getAllLeads' : ActorMethod<[], Array<Lead>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompany' : ActorMethod<[string], Company>,
  'getCompanyAssignmentsForLead' : ActorMethod<[string], Array<string>>,
  'getLead' : ActorMethod<[string], Lead>,
  'getLeadsAssignedToCompany' : ActorMethod<[string], Array<string>>,
  'getLeadsByStatus' : ActorMethod<[Status], Array<Lead>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeCompanyAssignment' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCompany' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'updateLead' : ActorMethod<
    [string, string, string, string, string, string, string, MoveSize, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];