 

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MoveSize = IDL.Variant({
  'studio' : IDL.Null,
  'twoBR' : IDL.Null,
  'oneBR' : IDL.Null,
  'threeBRPlus' : IDL.Null,
});
export const Time = IDL.Int;
export const Company = IDL.Record({
  'id' : IDL.Text,
  'contactName' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Status = IDL.Variant({
  'new' : IDL.Null,
  'closed' : IDL.Null,
  'distributed' : IDL.Null,
});
export const Lead = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : Status,
  'originAddress' : IDL.Text,
  'destinationAddress' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
  'moveDate' : IDL.Text,
  'moveSize' : MoveSize,
});

export const idlService = IDL.Service({
  'assignLeadToCompany' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createCompany' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'createLead' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        MoveSize,
        IDL.Text,
      ],
      [],
      [],
    ),
  'deleteCompany' : IDL.Func([IDL.Text], [], []),
  'deleteLead' : IDL.Func([IDL.Text], [], []),
  'getAllCompanies' : IDL.Func([], [IDL.Vec(Company)], ['query']),
  'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getCompany' : IDL.Func([IDL.Text], [Company], ['query']),
  'getCompanyAssignmentsForLead' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getLead' : IDL.Func([IDL.Text], [Lead], ['query']),
  'getLeadsAssignedToCompany' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getLeadsByStatus' : IDL.Func([Status], [IDL.Vec(Lead)], ['query']),
  'removeCompanyAssignment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateCompany' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateLead' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        MoveSize,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MoveSize = IDL.Variant({
    'studio' : IDL.Null,
    'twoBR' : IDL.Null,
    'oneBR' : IDL.Null,
    'threeBRPlus' : IDL.Null,
  });
  const Time = IDL.Int;
  const Company = IDL.Record({
    'id' : IDL.Text,
    'contactName' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Status = IDL.Variant({
    'new' : IDL.Null,
    'closed' : IDL.Null,
    'distributed' : IDL.Null,
  });
  const Lead = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : Status,
    'originAddress' : IDL.Text,
    'destinationAddress' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
    'moveDate' : IDL.Text,
    'moveSize' : MoveSize,
  });
  
  return IDL.Service({
    'assignLeadToCompany' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createCompany' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'createLead' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          MoveSize,
          IDL.Text,
        ],
        [],
        [],
      ),
    'deleteCompany' : IDL.Func([IDL.Text], [], []),
    'deleteLead' : IDL.Func([IDL.Text], [], []),
    'getAllCompanies' : IDL.Func([], [IDL.Vec(Company)], ['query']),
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getCompany' : IDL.Func([IDL.Text], [Company], ['query']),
    'getCompanyAssignmentsForLead' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getLead' : IDL.Func([IDL.Text], [Lead], ['query']),
    'getLeadsAssignedToCompany' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getLeadsByStatus' : IDL.Func([Status], [IDL.Vec(Lead)], ['query']),
    'removeCompanyAssignment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateCompany' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateLead' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          MoveSize,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };